version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: xvfb-run -a yarn lint

      - run: xvfb-run -a yarn test:ci

      - deploy:
         name: Deploy Master to Firebase
         command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            yarn deploy -- --token=$FIREBASE_DEPLOY_TOKEN
          fi
